GET /get/a6754e7c32a542fcb9a56ca598064be3?Expires=1469462161&KeyID=d06070b8&Signature=mG1VowjmkivEAhiSrCYbcaKgbsiO8nOWau4my%252BVZHZsQrSZZXG3wPG6zVkUuTc2TLKJhd9wP%2F3S3jcZ5Jd7eBA%253D%253D HTTP/1.0
Host: docs-sandbox.openprocurement.org


200 OK
Content-Disposition: attachment; filename=file.txt
Content-Type: text/plain; charset=UTF-8


