GET /get/c7cf326f09d44705be6cf67dd0017fd7?Expires=1469454319&KeyID=bc143495&Signature=KhHDph8Zw7YT9yq%252Biz19uB8KF4rZnlBJRssmyILKLLyRZV7M9QbN5uTu8QoceMi%252B3KWE4sK3rVgA%252BP22GgbrAg%253D%253D HTTP/1.0
Host: docs-sandbox.openprocurement.org


200 OK
Content-Disposition: attachment; filename=file.txt
Content-Type: text/plain; charset=UTF-8


