GET /get/5c521a51a3dc417e9c718fd4e6a85157?Expires=1467637367&KeyID=ad1c8f4f&Signature=MGYCMQCJc8ZgfJXH%252BvKGogrFZmqvgINEmVo1neZiSwIKDOhlvRxCBJBcytbsZYNnF%2Fs8wRECMQCdtfP%2FT4vd%252B49gvwR0GA1%2F17pqPlIIntdC8AzzYMzXWCKnDsCInX2LOzYcRzxi7kU%253D HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Host: docs.api-sandbox.openprocurement.org


200 OK
Content-Disposition: attachment; filename=file.txt
Content-Type: text/plain; charset=UTF-8


