POST /upload/a6754e7c32a542fcb9a56ca598064be3?KeyID=d06070b8&Signature=IMlA7SU1lQXGm7qGFBJQD7QEWv6K9ms9%2FcllUsQbbBLhWf48O5RVluaToch3Eopd%2FMoxXCozpL0gN6J65yeVCg%253D%253D HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 179
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy572732436472$
Host: docs-sandbox.openprocurement.org

------------a_BoUnDaRy572732436472$
Content-Disposition: form-data; name="file"; filename="file.txt"
Content-Type: text/plain

content
------------a_BoUnDaRy572732436472$--



200 OK
Content-Type: application/json; charset=UTF-8

{
  "get_url": "http://docs-sandbox.openprocurement.org/get/a6754e7c32a542fcb9a56ca598064be3?Expires=1469462161&KeyID=d06070b8&Signature=mG1VowjmkivEAhiSrCYbcaKgbsiO8nOWau4my%252BVZHZsQrSZZXG3wPG6zVkUuTc2TLKJhd9wP%2F3S3jcZ5Jd7eBA%253D%253D", 
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/a6754e7c32a542fcb9a56ca598064be3?KeyID=d06070b8&Signature=qwiE1zcGeR7bPSTawNedZ0yUrx0OeW4mL1HbctBRHDYSxGI9Zom8gR0JUZFwmOlpxkpps0AJhnJ7j%2FgNFqQeBA%253D%253D", 
    "format": "text/plain", 
    "hash": "md5:9a0364b9e99bb480dd25e1f0284c8555", 
    "title": "file.txt"
  }
}

