POST /upload HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 179
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy142627989259$
Host: docs-sandbox.openprocurement.org

------------a_BoUnDaRy142627989259$
Content-Disposition: form-data; name="file"; filename="file.txt"
Content-Type: text/plain

content
------------a_BoUnDaRy142627989259$--



200 OK
Content-Type: application/json; charset=UTF-8
Location: http://docs-sandbox.openprocurement.org/get/9a8d155e263d4ab58e89363c9d1b3050?Expires=1469115095&KeyID=e8946325&Signature=DVMXc0AFf8T9Hh5V%2FIn1KCUdYOKajUH%252BJZcVGRG3JGzKPgyzWfP%252BJJ6GEXvIvAGf%2FRCLUMWD8QCo3eZwez7RDw%253D%253D

{
  "get_url": "http://docs-sandbox.openprocurement.org/get/9a8d155e263d4ab58e89363c9d1b3050?Expires=1469115095&KeyID=e8946325&Signature=DVMXc0AFf8T9Hh5V%2FIn1KCUdYOKajUH%252BJZcVGRG3JGzKPgyzWfP%252BJJ6GEXvIvAGf%2FRCLUMWD8QCo3eZwez7RDw%253D%253D", 
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/9a8d155e263d4ab58e89363c9d1b3050?KeyID=e8946325&Signature=w%2FGtRAbYPYseo8KGgu1sSi%2FiPZajIDsSYMrQVkLhpj6bNOxbYP43GyLwWJAYgWiTihkd2Y6P%2FZPvzuxoblKqCw%253D%253D", 
    "format": "text/plain", 
    "hash": "md5:9a0364b9e99bb480dd25e1f0284c8555", 
    "title": "file.txt"
  }
}

